version: '3.8'

services:

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./env_variables.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.yoda.vm`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - pg_network

  db:
    image: postgres:12
    env_file:
      - ./env_variables.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    networks:
      - pg_network

<<<<<<< HEAD

=======
volumes:
    odoo-sessions:  # Define the named volume for sessions
    odoo-data:
>>>>>>> refs/remotes/origin/main

networks:
  pg_network:
    external: true
  traefik_proxy:
    external: true